#### This code has been written for AND Gate with two input 0 and 1
We will proceed in the following manner  : <br>
*Code for Forward propagation(0 hidden layer) <br>
*Code for Forward propagation(1 hidden layer)<br>
*Code for Neural Network with backpropagation (0 hidden layer)<br>
*Code for XOR Gate Neural Network with backpropagation (1 hidden layer)

# Forward propagation without any hidden layer

In [ ]:
import numpy as np

In [ ]:
#implementing AND function
X = np.array([[0,0], [0,1], [1,0], [1,1]])  
Y = np.array([[0,0,0,1]]).T
print("shape of x and y are :",X.shape, Y.shape)

In [ ]:
def sig(z):  #z=wx+b
    return 1/(1 + np.exp(-z))

In [1]:
#  output layer weights (as there is no hidden layer)
# np.random.random will give random number betwen 0 to 1
#so we'll be multiply it by 2, so range is now (0,2) and then subtract 1 to make range -1 to 1
weights = 2* np.random.random((2, 1)) - 1  #(2,1) is shape of array
bias = 2 * np.random.random(1) - 1
#here we have taken no of bias =1 as we're without any hidden layer and output layer has 1 unit
# but no of bias in each layer depends on the no of units in next consecutive layer
print("initial random wts and bias are : ",weights," ,", bias)
# forward propagation without any hidden layer
output0 = X  #output of 1st layer that is our output layer in this case
#output0 is output of input layer
z0=np.dot(output0, weights) + bias
print()
print("z for input layer is :",z0)
output = sig(z0) 
print()
print("output is" ,output)

shape of x and y are : (4, 2) (4, 1)
initial random wts and bias are :  [[0.62296978]
 [0.17629434]]  , [-0.03044741]

z for input layer is : [[-0.03044741]
 [ 0.14584692]
 [ 0.59252237]
 [ 0.7688167 ]]

output is [[0.49238873]
 [0.53639724]
 [0.64394368]
 [0.68326487]]


# Forward propagation with 1 hidden layer
taking 2 units in hidden layer and 2 units in input layer

In [2]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])  #implementing AND function
Y = np.array([[0,0,0,1]]).T

def sig(z): 
    return 1/(1 + np.exp(-z))

# one hidden layer weights and bias
wh = 2* np.random.random((2, 2)) - 1  #4wts required for output of input layer
bh = 2* np.random.random((1, 2)) - 1  
#output layer hidden weights and bias
wo = 2 * np.random.random((2, 1)) - 1 #2 wts required for output of hidden layer 
bo = 2 * np.random.random((1,1)) - 1

# forward propagation with one hidden layer
output0 = X
outputHidden = sig(np.dot(output0, wh) + bh) 
output = sig(np.dot(outputHidden, wo) + bo)
output


array([[0.53184492],
       [0.52157192],
       [0.51263876],
       [0.50518544]])

# Derivative of sigmoid function

In [36]:
def derivativeSig(z):
    return sig(z)*(1 - sig(z))

# Neural network code for 0 hidden layer

In [37]:
# forward propagation without hidden layer
import numpy as np

def grad_desc(output,weights,bias,X):
    lr=.1
    output0 = X 
    z0=np.dot(output0, weights) + bias
    output = sig(z0) 
    
    first_term=output-Y  #yp-ya
    input_for_last_layer = np.dot(output0, weights) + bias
    second_term = derivativeSig(input_for_last_layer)
    #we can also calculate second term by second_term=output(1-output)
    # as we have no hidden layer oj=output
    first_two = first_term * second_term
    
#     differentiation_E_wrt_W = np.array([[0.0],[0.0]]) # 2X1 dimension bcz original wt dimension is also 2,1

#     for i in range(2):
#         for j in range(4):
#             differentiation_E_wrt_W[i][0] += first_two[j][0] * output0[j][i]
#             #features are stored column wise in output, thats why i in 2nd place#
##########################
    #using matrix multiplication without for loop
    differentiation_E_wrt_W =np.dot(output0.T, first_two)
    weights=weights-lr*differentiation_E_wrt_W
    bias_change = np.sum(first_two)
##########################
    
#     bias_change = 0.0
#     for j in range(4):
#         bias_change += first_two[j][0] * 1
    bias = bias - lr * bias_change
    output = sig(np.dot(X, weights) + bias)

    return output,weights,bias




def run():
    X = np.array([[0,0], [0,1], [1,0], [1,1]]) 
    Y = np.array([[0,0,0,1]]).T
    def sig(z): 
        return 1/(1 + np.exp(-z))
    #initial random allocation
    weights = 2* np.random.random((2, 1)) - 1 
    bias = 2 * np.random.random(1) - 1
    
    
    output0 = X
    output = sig(np.dot(output0, weights) + bias)
    
    
    
    for i in range(10000):
        output,weights,bias=grad_desc(output,weights,bias,X)
    
    output = sig(np.dot(X, weights) + bias)
    
    print("output",output,"\n bias ",bias,"\n weight",weights)
    

In [38]:
run()

output [[2.46994059e-04]
 [5.57012712e-02]
 [5.57012722e-02]
 [9.33703391e-01]] 
 bias  [-8.30589925] 
 weight [[5.47545967]
 [5.47545965]]


In [39]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
a*b

array([ 1,  4,  9, 16])

# Neural network code for 1 hidden layer XOR Function

In [61]:
X = np.array([[0,0], [0,1], [1,0], [1,1]]) 
Y = np.array([[0,1,1,0]]).T

wh = 2* np.random.random((2, 2)) - 1 
bh = 2* np.random.random((1, 2)) - 1  
wo = 2 * np.random.random((2, 1)) - 1 
bo = 2 * np.random.random((1,1)) - 1
lr=0.1


###forward propagation###
output0 = X
input_hidden=np.dot(output0, wh) + bh
outputHidden = sig(input_hidden) 
input_outputLayer=np.dot(outputHidden, wo) + bo
output = sig(input_outputLayer)
################################

In [75]:
for i in range(10000):
    output0 = X
    input_hidden=np.dot(output0, wh) + bh
    outputHidden = sig(input_hidden) 
    input_outputLayer=np.dot(outputHidden, wo) + bo
    output = sig(input_outputLayer)
    
    
    
    first_term_output_layer=output-Y  #yp-ya
    second_term_output_layer = derivativeSig(input_outputLayer)
    first_two_output_layer = first_term_output_layer * second_term_output_layer

    first_term_hidden_layer= np.dot(first_two_output_layer,wo.T)
    second_term_hidden_layer=derivativeSig(input_hidden)
    first_two_hidden_layer=first_term_hidden_layer*second_term_hidden_layer

    weight_changes_output_layer=np.dot(outputHidden.T,first_two_output_layer)
    bias_changes_output_layer=np.sum(first_two_output_layer,axis=0,keepdims=True)

    weight_changes_hidden_layer=np.dot(output0.T,first_two_hidden_layer)
    bias_changes_hidden_layer=np.sum(first_two_hidden_layer,axis=0,keepdims=True)



    wo=wo-lr*weight_changes_output_layer
    bo=bo-lr*bias_changes_output_layer

    wh=wh-lr*weight_changes_hidden_layer
    bh=bh-lr*bias_changes_hidden_layer

output0 = X
input_hidden=np.dot(output0, wh) + bh
outputHidden = sig(input_hidden) 
input_outputLayer=np.dot(outputHidden, wo) + bo
output = sig(input_outputLayer)
output

array([[0.00896748],
       [0.99067134],
       [0.99066218],
       [0.01145033]])